spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backbone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.backbone: INFO
